/// Flutter icons BikenIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BikenIcons
///      fonts:
///       - asset: fonts/BikenIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class BikenIcons {
  BikenIcons._();

  static const _kFontFam = 'BikenIcons';
  static const _kFontPkg = null;

  static const IconData padlock_open_f =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hashtag_line =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData padlock_close =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question_fill =
      IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bike_fill =
      IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
